version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: urlshortener-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: urlshortener
    volumes:
      - mongodb_data:/data/db
    networks:
      - urlshortener-network

  redis:
    image: redis:7.2-alpine
    container_name: urlshortener-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - urlshortener-network

  app:
    build: .
    container_name: urlshortener-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_REDIS_HOST: redis
      APP_BASE_URL: http://localhost:8080
    depends_on:
      - mongodb
      - redis
    networks:
      - urlshortener-network

volumes:
  mongodb_data:
  redis_data:

networks:
  urlshortener-network:
    driver: bridge
